import {
  metamaskInstalled,
  connectWallet,
  getContract,
  getPlayerBalance,
  getWeb3,
  mintLBC,
  startGame,
  correctAnswer,
  incorrectAnswer,
  claimBalance,
  getOwner,
  getBalance,
  withdrawBalance,
  getContractBalance,
} from './contractMethods';
import questions from './questions';

export {
  questions,
  metamaskInstalled,
  connectWallet,
  getContract,
  getPlayerBalance,
  getWeb3,
  mintLBC,
  startGame,
  correctAnswer,
  incorrectAnswer,
  claimBalance,
  getOwner,
  getBalance,
  withdrawBalance,
  getContractBalance,
};
